### ISSUE TITLE
Un usuario sin categoria asignada accede a la ruta.

### ISSUE THREAD

**Issue by victornoriega** [kim-conaicdashian/proyecto_is2#1]
Cuando un usuario sin categoria asignada accede a la ruta /categoriaAsignada, el sistema regresa una excepción. Hay que validar o modificar los middleware correspondientes el encargado de plan de acción.

**Comment by JoseJFM** [comment]
Se introdujo un mensaje para un usuario que quiera ingresar sin ninguna categoría asignada.
