### ISSUE TITLE
Agregar recomendacion: redirecciona mal

### ISSUE THREAD

**Issue by victornoriega** [kim-conaicdashian/proyecto_is2#27]
La redirección se debe hacer adecuadamente pendejos. Si se agrega una recomendación, nos debería de mandar a la vista donde se agregó esa recomendación (recomendacion/show/{{id}})

**Comment by fabian6** [comment]
si nos dices pendejos,  tu deberias de redactar bien las cosas men, si no quedas como un pendejo. 
dices (recomendacion/show/{id} ) eso es la vista de una recomendacion en especifico, NO la vista que pides que es de donde se agrego. (notese mi falta de acentos en mi redaccion, pero tambien notese que  no te tacho de pendejo AMIGO)
