### ISSUE TITLE
Asociar correctamente categoría a encargado

### ISSUE THREAD

**Issue by victornoriega** [kim-conaicdashian/proyecto_is2#33]
Ahora mismo no funciona del todo bien la opcion
![image](https://user-images.githubusercontent.com/24713536/57514971-7398de00-72c6-11e9-8f88-f81c16b75d2e.png)
Yo les recomendaria que las categorias que deben aparecer como opcion son unicamente las que no tienen academico_id.

**Comment by JoseJFM** [comment]
El josechy
