### ISSUE TITLE
Categorias.show

### ISSUE THREAD

**Issue by victornoriega** [kim-conaicdashian/proyecto_is2#59]
![image](https://user-images.githubusercontent.com/24713536/57833619-3b364b80-776f-11e9-865f-aaa8403f2881.png)

Cualquiera esperaria que en la pestaña de Planes de acción, el botón de "agregar" sea para agregar un plan de acción.

**Comment by sebastianrs95** [comment]
ya esta esa madre, no es obvio porque esa es la tabla de los planes. Lo puse enseguida de cada recomendacion en la tabla de las recomendaciones
